FROM particle/buildpack-hal:0.0.14-gcc-arm-none-eabi-5_3-2016q1

ARG FIRMWARE_PATH
WORKDIR /
COPY bin /bin
COPY ${FIRMWARE_PATH} /firmware

ARG PLATFORM
ARG MODULAR
RUN /bin/prebuild-platform ${PLATFORM}
