#!/usr/bin/env bash

if [[ -z $FIRMWARE_PATH ]]; then
	FIRMWARE_PATH=`pwd`
fi

echo FIRMWARE_PATH=$FIRMWARE_PATH
BUILD_ROOT=$FIRMWARE_PATH

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

cp .dockerignore $BUILD_ROOT

# Read the defaults
source scripts/constants

if [ -z $DOCKER_IMAGE_NAME ]; then
	printf "${RED}You need to provide DOCKER_IMAGE_NAME${NC}\n"
	exit
fi

# Read firmware build configuration
source $FIRMWARE_PATH/.buildpackrc

source scripts/build-firmware-image
