#!/usr/bin/env bash

# Builds two images:
# 1. Base image containing the base buildpack and the scripts
# 2. Main image based on #1 with the DeviceOS repository

# Exit on errors
set -e

source scripts/functions

prepare_base_and_main_image ${BUILDPACK_BASE} \
    "${BUILDPACK_VERSION}-${BUILDPACK_VARIATION}" \
    $TAG
