#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
# Read the defaults
source scripts/constants

printf "${GREEN}Running tests inside of container...${NC} ${BUILD_PLATFORM[*]} \n"
rm -rf /home/travis/build/.build/
mkdir -p /home/travis/build/.build
docker run --env BUILD_PLATFORM="${BUILD_PLATFORM[*]}" --rm -v /home/travis/build/.build/:/firmware/test/unit_tests/.build/ -w /firmware $DOCKER_IMAGE_NAME-test /bin/run-tests
